### ISSUE TITLE
KVEC is not accessible

### ISSUE THREAD

**Issue by evildeeds** [fromtheexchange/image2svg-awesome#2]
kvec.de requires http authentication (maybe its no longer free?)

**Comment by fromtheexchange** [comment]
I noticed that too.  KVEC is older (it’s been around since 2001), and I think their hosting or website finally gave out.

The license states:
> This program is freeware (formerly licensed under the shareware concept).
> The program may be freely distributed, as long as it is complete.

So, you can probably go to the Internet Archive and download it from there https://web.archive.org/web/20211129215755/https://www.kvec.de/english/download.htm for now 👍

If the domain name expires, I’ll update the link to the Internet Archive version.

**Comment by evildeeds** [comment]
> I think their hosting or website finally gave out

Yeah; that could also be it. Anyway I wasn't really looking for a image vectorization tool specifically, but rather came across this during a survey for digital image processing pipeline utilities.

**Comment by fromtheexchange** [comment]
@evildeeds did you find any image vectorization tools we can add to the list? 😄
